create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('Punjabis', 'Polos', 'T-Shirts', 'Shirts')),
  price integer not null check (price >= 0),
  description text not null default '',
  image_url text not null default '',
  stock integer not null default 0 check (stock >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  phone text not null,
  address text not null,
  status text not null default 'New order' check (status in ('New order', 'Confirmed', 'Shipped', 'Delivered', 'Cancelled')),
  total integer not null check (total >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  price integer not null check (price >= 0),
  quantity integer not null default 1 check (quantity > 0)
);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "Products are publicly readable"
  on public.products for select using (true);

create policy "Anyone can create COD orders"
  on public.orders for insert with check (true);

create policy "Anyone can create order items"
  on public.order_items for insert with check (true);

create policy "Customers can read their own orders"
  on public.orders for select using (auth.uid() = user_id);

create policy "Customers can read their own order items"
  on public.order_items for select using (
    exists (select 1 from public.orders where orders.id = order_items.order_id and orders.user_id = auth.uid())
  );
