on thatcreate table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('Punjabis', 'Polos', 'T-Shirts', 'Shirts')),
  price integer not null check (price >= 0),
  description text not null default '',
  image_url text not null default '',
  stock integer not null default 0 check (stock >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  phone text not null,
  address text not null,
  status text not null default 'New order' check (status in ('New order', 'Confirmed', 'Shipped', 'Delivered', 'Cancelled')),
  total integer not null check (total >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  price integer not null check (price >= 0),
  quantity integer not null default 1 check (quantity > 0)
);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Admin access is granted only to the dedicated store account.
drop policy if exists "Products are publicly readable" on public.products;
drop policy if exists "Anyone can create COD orders" on public.orders;
drop policy if exists "Anyone can create order items" on public.order_items;
drop policy if exists "Customers can read their own orders" on public.orders;
drop policy if exists "Customers can read their own order items" on public.order_items;
drop policy if exists "Admin can manage products" on public.products;
drop policy if exists "Admin can view all orders" on public.orders;
drop policy if exists "Admin can update orders" on public.orders;
drop policy if exists "Admin can view all order items" on public.order_items;

create policy "Products are publicly readable"
  on public.products for select using (true);

create policy "Anyone can create COD orders"
  on public.orders for insert with check (true);

create policy "Anyone can create order items"
  on public.order_items for insert with check (true);

create policy "Customers can read their own orders"
  on public.orders for select using (auth.uid() = user_id);

create policy "Customers can read their own order items"
  on public.order_items for select using (
    exists (select 1 from public.orders where orders.id = order_items.order_id and orders.user_id = auth.uid())
  );

create policy "Admin can manage products"
  on public.products for all
  using (lower(auth.jwt() ->> 'email') = 'dilkashofficialbd@gmail.com')
  with check (lower(auth.jwt() ->> 'email') = 'dilkashofficialbd@gmail.com');

create policy "Admin can view all orders"
  on public.orders for select
  using (lower(auth.jwt() ->> 'email') = 'dilkashofficialbd@gmail.com');

create policy "Admin can update orders"
  on public.orders for update
  using (lower(auth.jwt() ->> 'email') = 'dilkashofficialbd@gmail.com')
  with check (lower(auth.jwt() ->> 'email') = 'dilkashofficialbd@gmail.com');

create policy "Admin can view all order items"
  on public.order_items for select
  using (lower(auth.jwt() ->> 'email') = 'dilkashofficialbd@gmail.com');

create or replace function public.create_cod_order(
  p_user_id uuid,
  p_customer_name text,
  p_phone text,
  p_address text,
  p_total integer,
  p_items jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_order_id uuid;
  item jsonb;
begin
  insert into public.orders (user_id, customer_name, phone, address, total)
  values (p_user_id, p_customer_name, p_phone, p_address, p_total)
  returning id into new_order_id;

  for item in select * from jsonb_array_elements(p_items)
  loop
    insert into public.order_items (order_id, product_id, product_name, price, quantity)
    values (
      new_order_id,
      case
        when exists (select 1 from public.products where id = (item ->> 'product_id')::bigint)
          then (item ->> 'product_id')::bigint
        else null
      end,
      item ->> 'product_name',
      (item ->> 'price')::integer,
      (item ->> 'quantity')::integer
    );
  end loop;

  return new_order_id;
end;
$$;

grant execute on function public.create_cod_order(uuid, text, text, text, integer, jsonb) to anon, authenticated;
